"use client";

import { useState } from "react";
import { Sparkles, Wand2 } from "lucide-react";

import { useChat } from "@/app/context/ChatContext";
import { useAura } from "@/app/context/AuraContext";

export default function AskAura() {
  const { addMessage } = useChat();

  const {
    setPrompt: setAuraPrompt,
    setGeneratedCode,
    setAiStatus,
  } = useAura();

  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setLoading(true);

    // Save prompt in Aura Context
    setAuraPrompt(prompt);

    // Update AI Status
    setAiStatus("Generating UI...");

    // Add user message
    addMessage("user", prompt);

    // Demo Generated React Component
    const demoCode = `export default function GeneratedComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-900">
      <div className="rounded-2xl bg-cyan-500 p-10 text-white shadow-2xl">
        <h1 className="text-3xl font-bold">
          ${prompt}
        </h1>

        <p className="mt-4">
          Generated by AuraGen AI
        </p>

        <button className="mt-6 rounded-lg bg-white px-6 py-3 font-semibold text-cyan-600">
          Get Started
        </button>
      </div>
    </div>
  );
}`;

    setTimeout(() => {
      // Update Editor
      setGeneratedCode(demoCode);

      // Update AI Status
      setAiStatus("Completed");

      // Assistant Reply
      addMessage(
        "assistant",
        "✅ UI generated successfully."
      );

      setLoading(false);
    }, 1000);
  };

  return (
    <section className="rounded-3xl border border-cyan-500/10 bg-slate-900/70 p-6 shadow-2xl">

      <div className="flex items-center gap-3">
        <Sparkles className="text-cyan-400" />

        <h2 className="text-xl font-bold text-white">
          Aura AI Copilot
        </h2>
      </div>

      <p className="mt-2 text-sm text-slate-400">
        Describe the interface you want AuraGen to build.
      </p>

      <textarea
        rows={6}
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Example: Build a modern analytics dashboard with charts and dark theme..."
        className="mt-5 w-full rounded-2xl border border-slate-700 bg-slate-950 p-4 text-white outline-none focus:border-cyan-500"
      />

      <button
        onClick={handleGenerate}
        disabled={loading}
        className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-violet-500 py-3 font-semibold text-white transition hover:opacity-90 disabled:opacity-50"
      >
        <Wand2 size={18} />

        {loading ? "Generating..." : "Generate UI"}
      </button>

    </section>
  );
}