"use client";

import { useState } from "react";
import { Sparkles, Wand2 } from "lucide-react";

import { useChat } from "@/app/context/ChatContext";
import { useAura } from "@/app/context/AuraContext";
import toast from "react-hot-toast";
import { useTelemetryContext } from "../context/TelemetryContext";

import { generateAuraCode } from "../services/aiService";

export default function AskAura() {
  const { addMessage } = useChat();
  const { telemetry } = useTelemetryContext();
  
  const {
    setPrompt: setAuraPrompt,
    setGeneratedCode,
    setAiStatus,
    addGeneratedComponent,
  } = useAura();

  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    const loadingToast = toast.loading("Generating UI...");

    setAuraPrompt(prompt);

    setAiStatus("Generating UI...");

    addMessage("user", prompt);

    try {
      const res = await generateAuraCode(prompt, {
  hesitation: telemetry.hesitationTime,
  clicks: telemetry.clicks,
});

      const jsx = res.code;

      setGeneratedCode(jsx);
      console.log("Cognitive Load:", res.cognitiveLoad);
console.log("Stress Level:", res.stressLevel);
console.log("Focus Score:", res.focusScore);

      addGeneratedComponent({
        id: Date.now(),
        title: prompt,
        description: "Generated by Aura AI",
        jsx,
      });

      setAiStatus("Completed");

      addMessage(
        "assistant",
        "✅ UI generated successfully."
      );
      toast.dismiss(loadingToast);

toast.success(res.response);
setPrompt("");

    } catch (err: any) {

      console.error(err);

      setAiStatus("Failed");

      addMessage(
        "assistant",
        "❌ Failed to generate UI."
      );

      toast.dismiss(loadingToast);

toast.error(
  err?.response?.data?.message ||
  "Unable to connect to backend."
);

    } finally {

      toast.dismiss(loadingToast);

setLoading(false);

    }
  };
    return (
    <section className="rounded-3xl border border-cyan-500/10 bg-slate-900/70 p-6 shadow-2xl">

      <div className="flex items-center gap-3">

        <Sparkles className="text-cyan-400" />

        <h2 className="text-xl font-bold text-white">
          Aura AI Copilot
        </h2>

      </div>

      <p className="mt-2 text-sm text-slate-400">
        Describe the interface you want AuraGen to build.
      </p>

      <textarea
        rows={6}
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Example: Build a modern analytics dashboard with charts and dark theme..."
        className="mt-5 w-full rounded-2xl border border-slate-700 bg-slate-950 p-4 text-white outline-none focus:border-cyan-500"
      />

      <button
        onClick={handleGenerate}
        disabled={loading}
        className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-violet-500 py-3 font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
      >

        <Wand2 size={18} />

        {loading ? "Generating..." : "Generate UI"}

      </button>

    </section>
  );
}